name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  SESSION: ${{ secrets.SESSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC 12
        shell: bash
        run: |
          sudo apt update
          sudo apt install gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Create default Conan profile
        run: conan profile new default --detect

      - name: Update Conan profile
        run: |
          conan profile update settings.build_type=${{env.BUILD_TYPE}} default
          conan profile update settings.compiler.cppstd=20 default
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - uses: actions/cache@v3
        with:
          path: ~/.conan/
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}

      - name: Install dependencies
        run: conan install . --build=missing --install-folder=${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Solve user puzzles
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ./aoc21 | tee solutions.txt

      - name: Upload solutions
        uses: actions/upload-artifact@v2
        with:
          name: solutions.txt
          path: ${{github.workspace}}/build/solutions.txt
